#!/bin/bash

echo "
{
  \"restartCycle\": $SELGRID_RESTART_CYCLE,
  \"customProcessHandler\": \"com.paypal.selion.utils.process.UnixProcessHandler\",
  \"artifactMaxFileSize\": 1073741824,
  \"artifactExpiryInMilliSec\": 86400000,
  \"managedArtifact\": \"com.paypal.selion.grid.servlets.transfer.DefaultManagedArtifact\",
  \"managedArtifactBaseDir\": \"repository\",
  \"nodeAuthToken\": $SELGRID_NODE_AUTH,
  \"selendroidDefaultArgs\": {
      \"-logLevel\": \"WARNING\",
      \"-deviceScreenshot\": \"\",
      \"-keepEmulator\": \"\",
      \"-deviceLog\": false,
      \"-maxSession\": 1,
      \"-proxy\": \"io.selendroid.grid.SelendroidSessionProxy\",
      \"-port\": 5557
  },
  \"appiumDefaultArgs\" : {
      \"--port\": 5558,
      \"--log-timestamp\": \"\",
      \"--log-level\": \"info\"
  }
}"
