#!/bin/bash

echo "
{
  \"servlets\": [
      \"com.paypal.selion.grid.servlets.LoginServlet\",
      \"com.paypal.selion.grid.servlets.ListAllNodes\",
      \"com.paypal.selion.grid.servlets.GridAutoUpgradeDelegateServlet\",
      \"com.paypal.selion.grid.servlets.GridForceRestartDelegateServlet\",
      \"com.paypal.selion.grid.servlets.PasswordChangeServlet\",
      \"com.paypal.selion.grid.servlets.TransferServlet\"
  ],
  \"host\": null,
  \"port\": 4444,
  \"prioritizer\": null,
  \"capabilityMatcher\": \"com.paypal.selion.grid.matchers.MobileCapabilityMatcher\",
  \"throwOnCapabilityNotPresent\": true,
  \"newSessionWaitTimeout\": $GRID_NEW_SESSION_WAIT_TIMEOUT,
  \"jettyMaxThreads\": $GRID_JETTY_MAX_THREADS,
  \"nodePolling\": $GRID_NODE_POLLING,
  \"cleanUpCycle\": $GRID_CLEAN_UP_CYCLE,
  \"timeout\": $GRID_TIMEOUT,
  \"browserTimeout\": $GRID_BROWSER_TIMEOUT,
  \"maxSession\": $GRID_MAX_SESSION,
  \"unregisterIfStillDownAfter\": $GRID_UNREGISTER_IF_STILL_DOWN_AFTER
}"
